#!/usr/bin/env ruby

if ENV['HTTP_HOST']
  require 'cgi'
  q = CGI.new
  regexp = q['q'].to_s.strip
  puts "Content-Type: text/plain\r\n\r\n"
else
  regexp = ARGV[0]
  if !regexp
    STDERR.puts "Usage: cref <regexp>"
    exit 1
  end
end

reg = /(^|\t)#{regexp}(\t|$)/

Dir.glob(File.dirname($0) + '/*.tsv').each do |tsv|
  lines = File.readlines(tsv)
  title, *header = *lines.shift.chomp.split("\t")

  first_tsv = true
  lines.each do |line|
    line.chomp!
    if reg =~ line
      if first_tsv
        puts "\n=== #{title} ==="
        first_tsv = false
      end

      puts
      name, *values = *line.split("\t")
      puts "* #{name}"
      header.zip(values).each do |h, v|
        puts "#{h}: #{v}"
      end
    end
  end
end
